name: DragonSpawn
main: com.miraclem4n.dragonspawn.DragonSpawn
version: ${m.version}-${build.number}-${p.version}
website: http://mdev.in
author: MiracleM4n
description: Random Dragon Spawning
commands:
    dragonspawn:
        description: Main Command
        usage: |
            /<command> reload - Reloads the config.
        aliases: [dragons, ds]
