name: DragonSpawn
main: in.mDev.MiracleM4n.DragonSpawn.DragonSpawn
version: ${m.version}-${build.number}-${m.version}
website: 
author: MiracleM4n
softdepend: [Spout]
description: Random Dragon Spawning
commands:
    dragonspawn:
        description: Main Command
        usage: |
            /<command> reload - Reloads the config.
        aliases: [dragons, ds]
